#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppNBA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="nbadb")]
	public partial class NBAContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertJugador(Jugador instance);
    partial void UpdateJugador(Jugador instance);
    partial void DeleteJugador(Jugador instance);
    partial void InsertEquipo(Equipo instance);
    partial void UpdateEquipo(Equipo instance);
    partial void DeleteEquipo(Equipo instance);
    #endregion
		
		public NBAContextDataContext() : 
				base(global::AppNBA.Properties.Settings.Default.nbadbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NBAContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NBAContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NBAContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NBAContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Jugador> Jugador
		{
			get
			{
				return this.GetTable<Jugador>();
			}
		}
		
		public System.Data.Linq.Table<Equipo> Equipo
		{
			get
			{
				return this.GetTable<Equipo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.player")]
	public partial class Jugador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private string _apellidos;
		
		private string _equipo;
		
		private string _position;
		
		private string _dateOfBirth;
		
		private string _height;
		
		private string _weight;
		
		private string _jerseyNumber;
		
		private string _age;
		
		private System.Nullable<decimal> _careerPoints;
		
		private System.Nullable<decimal> _careerBlocks;
		
		private System.Nullable<decimal> _carrerAssists;
		
		private System.Nullable<decimal> _careerRebounds;
		
		private System.Nullable<decimal> _careerTurnovers;
		
		private System.Nullable<decimal> _careerPercentageThree;
		
		private System.Nullable<decimal> _careerPercentageFreethrow;
		
		private System.Nullable<decimal> _careerPercentageFieldGoal;
		
		private string _headShotUrl;
		
		private string _dateLastUpdated;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OnequipoChanging(string value);
    partial void OnequipoChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    partial void OndateOfBirthChanging(string value);
    partial void OndateOfBirthChanged();
    partial void OnheightChanging(string value);
    partial void OnheightChanged();
    partial void OnweightChanging(string value);
    partial void OnweightChanged();
    partial void OnjerseyNumberChanging(string value);
    partial void OnjerseyNumberChanged();
    partial void OnageChanging(string value);
    partial void OnageChanged();
    partial void OncareerPointsChanging(System.Nullable<decimal> value);
    partial void OncareerPointsChanged();
    partial void OncareerBlocksChanging(System.Nullable<decimal> value);
    partial void OncareerBlocksChanged();
    partial void OncarrerAssistsChanging(System.Nullable<decimal> value);
    partial void OncarrerAssistsChanged();
    partial void OncareerReboundsChanging(System.Nullable<decimal> value);
    partial void OncareerReboundsChanged();
    partial void OncareerTurnoversChanging(System.Nullable<decimal> value);
    partial void OncareerTurnoversChanged();
    partial void OncareerPercentageThreeChanging(System.Nullable<decimal> value);
    partial void OncareerPercentageThreeChanged();
    partial void OncareerPercentageFreethrowChanging(System.Nullable<decimal> value);
    partial void OncareerPercentageFreethrowChanged();
    partial void OncareerPercentageFieldGoalChanging(System.Nullable<decimal> value);
    partial void OncareerPercentageFieldGoalChanged();
    partial void OnheadShotUrlChanging(string value);
    partial void OnheadShotUrlChanged();
    partial void OndateLastUpdatedChanging(string value);
    partial void OndateLastUpdatedChanged();
    #endregion
		
		public Jugador()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="firstName", Storage="_nombre", DbType="VarChar(255)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="lastName", Storage="_apellidos", DbType="VarChar(255)")]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="team", Storage="_equipo", DbType="VarChar(255)")]
		public string equipo
		{
			get
			{
				return this._equipo;
			}
			set
			{
				if ((this._equipo != value))
				{
					this.OnequipoChanging(value);
					this.SendPropertyChanging();
					this._equipo = value;
					this.SendPropertyChanged("equipo");
					this.OnequipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(255)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this.OnpositionChanging(value);
					this.SendPropertyChanging();
					this._position = value;
					this.SendPropertyChanged("position");
					this.OnpositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOfBirth", DbType="VarChar(255)")]
		public string dateOfBirth
		{
			get
			{
				return this._dateOfBirth;
			}
			set
			{
				if ((this._dateOfBirth != value))
				{
					this.OndateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._dateOfBirth = value;
					this.SendPropertyChanged("dateOfBirth");
					this.OndateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height", DbType="VarChar(255)")]
		public string height
		{
			get
			{
				return this._height;
			}
			set
			{
				if ((this._height != value))
				{
					this.OnheightChanging(value);
					this.SendPropertyChanging();
					this._height = value;
					this.SendPropertyChanged("height");
					this.OnheightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weight", DbType="VarChar(255)")]
		public string weight
		{
			get
			{
				return this._weight;
			}
			set
			{
				if ((this._weight != value))
				{
					this.OnweightChanging(value);
					this.SendPropertyChanging();
					this._weight = value;
					this.SendPropertyChanged("weight");
					this.OnweightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jerseyNumber", DbType="VarChar(255)")]
		public string jerseyNumber
		{
			get
			{
				return this._jerseyNumber;
			}
			set
			{
				if ((this._jerseyNumber != value))
				{
					this.OnjerseyNumberChanging(value);
					this.SendPropertyChanging();
					this._jerseyNumber = value;
					this.SendPropertyChanged("jerseyNumber");
					this.OnjerseyNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="VarChar(255)")]
		public string age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this.OnageChanging(value);
					this.SendPropertyChanging();
					this._age = value;
					this.SendPropertyChanged("age");
					this.OnageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_careerPoints", DbType="Decimal(4,1)")]
		public System.Nullable<decimal> careerPoints
		{
			get
			{
				return this._careerPoints;
			}
			set
			{
				if ((this._careerPoints != value))
				{
					this.OncareerPointsChanging(value);
					this.SendPropertyChanging();
					this._careerPoints = value;
					this.SendPropertyChanged("careerPoints");
					this.OncareerPointsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_careerBlocks", DbType="Decimal(4,1)")]
		public System.Nullable<decimal> careerBlocks
		{
			get
			{
				return this._careerBlocks;
			}
			set
			{
				if ((this._careerBlocks != value))
				{
					this.OncareerBlocksChanging(value);
					this.SendPropertyChanging();
					this._careerBlocks = value;
					this.SendPropertyChanged("careerBlocks");
					this.OncareerBlocksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carrerAssists", DbType="Decimal(4,1)")]
		public System.Nullable<decimal> carrerAssists
		{
			get
			{
				return this._carrerAssists;
			}
			set
			{
				if ((this._carrerAssists != value))
				{
					this.OncarrerAssistsChanging(value);
					this.SendPropertyChanging();
					this._carrerAssists = value;
					this.SendPropertyChanged("carrerAssists");
					this.OncarrerAssistsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_careerRebounds", DbType="Decimal(4,1)")]
		public System.Nullable<decimal> careerRebounds
		{
			get
			{
				return this._careerRebounds;
			}
			set
			{
				if ((this._careerRebounds != value))
				{
					this.OncareerReboundsChanging(value);
					this.SendPropertyChanging();
					this._careerRebounds = value;
					this.SendPropertyChanged("careerRebounds");
					this.OncareerReboundsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_careerTurnovers", DbType="Decimal(4,1)")]
		public System.Nullable<decimal> careerTurnovers
		{
			get
			{
				return this._careerTurnovers;
			}
			set
			{
				if ((this._careerTurnovers != value))
				{
					this.OncareerTurnoversChanging(value);
					this.SendPropertyChanging();
					this._careerTurnovers = value;
					this.SendPropertyChanged("careerTurnovers");
					this.OncareerTurnoversChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_careerPercentageThree", DbType="Decimal(4,1)")]
		public System.Nullable<decimal> careerPercentageThree
		{
			get
			{
				return this._careerPercentageThree;
			}
			set
			{
				if ((this._careerPercentageThree != value))
				{
					this.OncareerPercentageThreeChanging(value);
					this.SendPropertyChanging();
					this._careerPercentageThree = value;
					this.SendPropertyChanged("careerPercentageThree");
					this.OncareerPercentageThreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_careerPercentageFreethrow", DbType="Decimal(4,1)")]
		public System.Nullable<decimal> careerPercentageFreethrow
		{
			get
			{
				return this._careerPercentageFreethrow;
			}
			set
			{
				if ((this._careerPercentageFreethrow != value))
				{
					this.OncareerPercentageFreethrowChanging(value);
					this.SendPropertyChanging();
					this._careerPercentageFreethrow = value;
					this.SendPropertyChanged("careerPercentageFreethrow");
					this.OncareerPercentageFreethrowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_careerPercentageFieldGoal", DbType="Decimal(4,1)")]
		public System.Nullable<decimal> careerPercentageFieldGoal
		{
			get
			{
				return this._careerPercentageFieldGoal;
			}
			set
			{
				if ((this._careerPercentageFieldGoal != value))
				{
					this.OncareerPercentageFieldGoalChanging(value);
					this.SendPropertyChanging();
					this._careerPercentageFieldGoal = value;
					this.SendPropertyChanged("careerPercentageFieldGoal");
					this.OncareerPercentageFieldGoalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_headShotUrl", DbType="VarChar(255)")]
		public string headShotUrl
		{
			get
			{
				return this._headShotUrl;
			}
			set
			{
				if ((this._headShotUrl != value))
				{
					this.OnheadShotUrlChanging(value);
					this.SendPropertyChanging();
					this._headShotUrl = value;
					this.SendPropertyChanged("headShotUrl");
					this.OnheadShotUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateLastUpdated", DbType="VarChar(255)")]
		public string dateLastUpdated
		{
			get
			{
				return this._dateLastUpdated;
			}
			set
			{
				if ((this._dateLastUpdated != value))
				{
					this.OndateLastUpdatedChanging(value);
					this.SendPropertyChanging();
					this._dateLastUpdated = value;
					this.SendPropertyChanged("dateLastUpdated");
					this.OndateLastUpdatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.team")]
	public partial class Equipo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _conference;
		
		private string _record;
		
		private string _teamLogoUrl;
		
		private string _dateLastUpdated;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnconferenceChanging(string value);
    partial void OnconferenceChanged();
    partial void OnrecordChanging(string value);
    partial void OnrecordChanged();
    partial void OnteamLogoUrlChanging(string value);
    partial void OnteamLogoUrlChanged();
    partial void OndateLastUpdatedChanging(string value);
    partial void OndateLastUpdatedChanged();
    #endregion
		
		public Equipo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conference", DbType="VarChar(255)")]
		public string conference
		{
			get
			{
				return this._conference;
			}
			set
			{
				if ((this._conference != value))
				{
					this.OnconferenceChanging(value);
					this.SendPropertyChanging();
					this._conference = value;
					this.SendPropertyChanged("conference");
					this.OnconferenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_record", DbType="VarChar(255)")]
		public string record
		{
			get
			{
				return this._record;
			}
			set
			{
				if ((this._record != value))
				{
					this.OnrecordChanging(value);
					this.SendPropertyChanging();
					this._record = value;
					this.SendPropertyChanged("record");
					this.OnrecordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamLogoUrl", DbType="VarChar(255)")]
		public string teamLogoUrl
		{
			get
			{
				return this._teamLogoUrl;
			}
			set
			{
				if ((this._teamLogoUrl != value))
				{
					this.OnteamLogoUrlChanging(value);
					this.SendPropertyChanging();
					this._teamLogoUrl = value;
					this.SendPropertyChanged("teamLogoUrl");
					this.OnteamLogoUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateLastUpdated", DbType="VarChar(255)")]
		public string dateLastUpdated
		{
			get
			{
				return this._dateLastUpdated;
			}
			set
			{
				if ((this._dateLastUpdated != value))
				{
					this.OndateLastUpdatedChanging(value);
					this.SendPropertyChanging();
					this._dateLastUpdated = value;
					this.SendPropertyChanged("dateLastUpdated");
					this.OndateLastUpdatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
